# Generated by Django 5.1 on 2024-09-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
    ]
