# Generated by Django 5.1 on 2024-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='descripcion',
            field=models.CharField(default='Descripción no disponible', max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='media/nomy/images/default.jpeg', upload_to='media/nomy/images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitud',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitud',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
