# Generated by Django 5.1 on 2024-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_descripcion_alter_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
